### ISSUE TITLE
Checkout Action in Bootes.x CodeQL workflow points at wrong ref

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFS#346]
**Checklist (Please check before submitting)**

* [ ] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [ ] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
When updating the checkout action references we accidentally changed the ref for checking out the codeQL repository itself. 

Fix is to simply remove the "ref" key from the CodeQL checkout step in the coding standard job. 

**To Reproduce**
See <https://github.com/nasa/cFS/actions/runs/1162811311>

**Expected behavior**
Clean Run

**Code snips**

```yml
      - name: Checkout codeql code      
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: actions/checkout@v2
        with:
          repository: github/codeql 
          submodules: true 
          path: codeql
          ref: bootes.x
```

**System observed on:**
Ubuntu CI
