### ISSUE TITLE
Use cpp as CodeQL Language

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [nasa/cFS#469]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
The codeql-reusable.yml workflow uses C as the language, which is not a valid option. It should be cpp instead. 

**Expected behavior**
Use cpp as the CodeQL language. 

**Code snips**
```
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: c
          config-file: nasa/cFS/.github/codeql/codeql-${{matrix.scan-type}}.yml@main
```

**Reporter Info**
Ariel Adams, ASRC Federal
